---
:config:
  :graphite_url: http://graphite-global.phx.weave.mozilla.com
  :default_colors:
    ["blue", "green", "yellow", "red", "purple", "brown", "aqua", "gold"]
  :url_opts:
    :width: 1000
    :height: 400
    :fontSize: 15
    :start: "8 hours ago" # chronic timespec
    :template: "noc"
    :yMin: 0
    :margin: 5
    :thickness: 2

  :refresh_rate: 60 # fixme make this a chronic interval
  :host_sort: "numeric"
  #:date_format: "%s" # easiest format for humans to read
